### ISSUE TITLE
Support URL sharing and no-JS form submissions

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [AleksandrHovhannisyan/fluid-type-scale-calculator#17]
## Description

This ticket is to support two related enhancements:

- URL sharing
- No-JS form submissions

When a user changes the parameters in the form, the app should update its URL with the serialized query parameters, thus allowing them to share the URL. On page request, the app would read those query parameters on the server side and use them to populate the app's initial state.

The app should also support no-JS form submissions for the (admittedly rare) case where a user may have JavaScript disabled. In that case, on form submission, users should be redirected to a page whose URL consists of query parameters assembled from the form's data.

## Requirements

- `name`s for all of the inputs
- a form `action` pointing to a dynamic route
- the 11ty serverless plugin

The basic idea is then to supply the 11ty serverless query params to the React component and use those to initialize its state. SSR will then return the code output.

## Additional context, ideas, or considerations

- Not currently possible with Slinkity because it does not work with 11ty Serverless.
- If and when this is possible, XSS will need to be defended against very carefully.
- Easy to implement if we migrate to a framework like Next.js.

**Comment by dangelion** [comment]
Your calculator is awesome, I like it more than Utopia because I can customize the CSS variables names!

I think is missing just adding query params to the URL so navigating that URL I find the form pre-filled, like this:
https://utopia.fyi/type/calculator/?c=320,16,1.125,1920,20,1.333,5,2,&s=0.75%7C0.5%7C0.25,1.5%7C2%7C3%7C4%7C6,s-l

Is this possible?

Also, why talking only about type/font-size, while this could be used also for spacings and other?

Thanks

**Comment by AleksandrHovhannisyan** [comment]
Thanks! That's awesome to hear.

Yeah, I agree that URL params would be great for sharing URLs. If Slinkity and 11ty Serverless could work together one day, I'd be able to implement this quite easily. Alternatively, I could maybe consider migrating to Next.js in the meantime. It probably wouldn't be much of a headache since I'm already using React.

> Also, why talking only about type/font-size, while this could be used also for spacings and other?

Great question! I originally wanted to make a tool to help me with fluid font sizing since some of the other tools out there were missing things I wanted. But it wasn't until later that I realized it could be used for anything (especially since you can use a custom naming convention). Right now, the focus is still on creating a fluid "type" scale mainly for SEO reasons, but you're spot on: You can technically use it for anything 😄 

(Fun fact: The app uses its own output for fluid spacing _and_ font sizing in the UI.)

**Comment by dangelion** [comment]
@AleksandrHovhannisyan Really happy to hear that this feature is on the road. Can't wait to see it, hopefully soon. Thanks again for your work.

**Comment by AleksandrHovhannisyan** [comment]
WIP migration to Next.js here: https://github.com/AleksandrHovhannisyan/fluid-type-scale-calculator/tree/nextjs-migration

But I will likely abandon it because it's too bloated compared to the original app.

Will explore other options.

**Comment by AleksandrHovhannisyan** [comment]
Closed via #20
