### ISSUE TITLE
Support container queries

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [AleksandrHovhannisyan/fluid-type-scale-calculator#48]
## Description/user story

Concept: https://www.robinrendle.com/notes/container-queries-and-typography/

- [x] Add a new parameter to the schema to opt into using `cqw` over `vw`
- [x] Update existing code to use `cqw` if that parameter is set
- [x] Update existing references to "screen" or "viewport" width as needed in form labels
- [x] Update fallback label to mention feature queries, if relevant
- [x] Test for `cqw` support with feature queries if user opts in

**Comment by Anunnaki26** [comment]
It would be better if the font size was calculated using a linear function in my opinion.
For example:
If the width of the container is 14rem then the font size should be 1rem. If the container is 60rem wide, then the font size should be 1.25rem.
Then you could calculate a linear function using the two points (14/1) and (60/1.25) and the font size should then change depending on the width of the container and the font size set by the user in the browser.
What do you say to this?

For example:

p {
	font-size: calc((100cqi/280) + 17px) / 16 * 1rem;
}

**Comment by AleksandrHovhannisyan** [comment]
@Wahrheit26 To clarify, my proposal would still use linear interpolation, but instead of it being between two screen widths, it would just be between two container widths, and instead of `vw` we would use `cqw` (or `cqi`).

**Comment by AleksandrHovhannisyan** [comment]
Shipped in #52
