### ISSUE TITLE
Input type range bug,  slider maxing out on 100.

### ISSUE THREAD

**Issue by Profana92** [AleksandrHovhannisyan/fluid-type-scale-calculator#51]
## Description

Input field range no max value. It is always 100. 

## Steps to Reproduce

1. Change screen width to 1440px for example.
2. Use input type range.
3. Input number field max out on 100, what is 100px, meaning font sizes never change.

## Expected Behavior

Fonts should change with input type range.

## Additional context (if applicable)

<input id="screen-width-range" class="RangeInput_range-slider__ooLUz" min="0" type="range" aria-invalid="false" value="1304">

lack of max="1440" attribute (or any other picked by user screen width.

**Comment by AleksandrHovhannisyan** [comment]
Thanks for reporting this! I'm able to reproduce the issue. That likely regressed very recently when #50 was merged. I'll take a look.

**Comment by AleksandrHovhannisyan** [comment]
Should be good in a minute or two after the site rebuilds. Let me know if you still see the issue.

**Comment by Profana92** [comment]
Just tested, it is fixed, thank you and have a great day :)
